openapi: 3.0.0
info:
  title: Corporate Hotel Booking API
  description: HTTP API for the Corporate Hotel Booking service
  contact:
    email: islomar@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/islomar/CorporateHotelBooking/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://127.0.0.1:8080/v1
  description: Local Mocking
paths:
  /booking:
    post:
      summary: create a booking
      description: Adds an item to the system
      operationId: saveBooking  
      requestBody:
        description: Booking item to add
        content:
          application/json:
            schema:
                  $ref: '#/components/schemas/BookingRequest'
      responses:
        "201":
          description: booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse' 
              example: 
                bookingId: f727fd25-864e-3a7b-9fbf-d2d852fdac1b
        "400":
          description: invalid input, object invalid
        "409":
          description: an identical booking already exists
      x-swagger-router-controller: Developers
components:
  schemas:
    BookingRequest:
      type: object
      required:
        - employeeId
        - hotelId
        - roomType
      properties:
        employeeId:
          type: string
          example: JOSE_CABRERA
        hotelId:
          type: string
          example: FOUR_SEASONS_HAWAI_BEACH            
        roomType:
          type: string
          example: DOUBLE          
      example:
        employeeId: JOSE_CABRERA
        hotelId: FOUR_SEASONS_HAWAI_BEACH
        roomType: DOUBLE            
    BookingResponse:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
          example: f727fd25-864e-3a7b-9fbf-d2d852fdac1b
      example:
        bookingId: f727fd25-864e-3a7b-9fbf-d2d852fdac1b